# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ab7af0340bc5b97f6969ee5ecc4a35fb347fdfa176cc9b5ebbcaeec7f3171f130ea483457312d6eaae4e313d884769036a16b71310bd64eaeb1d1266dc6de91

test:
  secret_key_base: 4ab4f27441788cd3a8709eb1b0bf1b72aa1eee74cd51a574285275e0dabf6eac63cd1f87c835123acc1cdbb33ed82f0fd3e5ac9bf257c56f6804e85df25015c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
